### ISSUE TITLE
How to run in Docker?

### ISSUE THREAD

**Issue by ThinkPadNL** [zivillian/enverproxy#2]
Most of my homelab stuff is running in Docker. I was trying to create a Docker image for this project, but so far i cannot get it running. This is the Dockerfile i made:

     FROM python:3.9-alpine
     RUN apk --no-cache add git
     RUN pip3 install paho-mqtt
     RUN git clone https://github.com/zivillian/enverproxy.git /data/app
     RUN ls -a /data/app
     RUN sed -i "s|/etc/enverproxy.conf|/data/app/enverproxy.conf|g" /data/app/enverproxy.py 
     WORKDIR /data/app
     EXPOSE 1898
     CMD ["./enverproxy.py"]
     ENTRYPOINT ["python3"]

The image builds succesfully, but when i try to run a container based on this image, i get this error:

     Traceback (most recent call last):
       File "/data/app/./enverproxy.py", line 309, in <module>
         server.connect_mqtt(config['enverproxy']['mqtthost'], config['enverproxy']['mqttuser'], config['enverproxy']['mqttpassword'],                          int(config['enverproxy']['mqttport']))
       File "/data/app/./enverproxy.py", line 69, in connect_mqtt
         self.mqtt.connect(host, port)
       File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
         return self.reconnect()
       File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
         sock = self._create_socket_connection()
       File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
         return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
       File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
         raise err
       File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
         sock.connect(sa)
     OSError: [Errno 99] Address not available`

I have port 1898 exposed in the container.

Any ideas how to get this working in Docker?

**Comment by ThinkPadNL** [comment]
Ok i got the container to run. I was a bit dumb actually, i forgot to point the script to my MQTT-server 😆 
This is the Dockerfile that works to create an image that at least gets the container running:

      FROM python:3.9-alpine
      RUN apk --no-cache add git
      RUN pip3 install paho-mqtt
      RUN git clone https://github.com/zivillian/enverproxy.git /data/app
      RUN sed -i "s|/etc/enverproxy.conf|/data/app/enverproxy.conf|g" /data/app/enverproxy.py 
      RUN sed -i "s|mqtthost     = localhost|mqtthost     = 192.168.1.32|g" /data/app/enverproxy.conf 
      WORKDIR /data/app
      EXPOSE 1898
      CMD ["./enverproxy.py"]
      ENTRYPOINT ["python3"]

I cannot test further as i don't have a Enverbridge in my possession yet. Will arrive later this week.
I think i will also add the Python script from [this](https://sven.stormbind.net/blog/posts/iot_envertech_enverbridge_evb202/) blog to the container so that i can also add the micro-inverters to the bridge without having to use the obscure Chinese windows software.

**Comment by ThinkPadNL** [comment]
@zivillian I see in https://github.com/zivillian/enverproxy/blob/5888348df6c8aa6fcfd55dc85d5e60000d4da98e/enverproxy.conf#L29 that no forward IP is defined. Does this mean that with the Enverbridge in mode 'local', nothing is sent to the internet? I am planning to block internet traffic for the Enverbridge completely in my firewall (Chinese IOT stuff, blegh! 😆 ).
Do i need to make changes to the script or is it already kept local-only with the current status of the script?

**Comment by zivillian** [comment]
There is nothing more to do - I had this setup running for the last 6 months on a network without internet access.

**Comment by ThinkPadNL** [comment]
Received the EVB202 today and configured the local server mode etc. I exposed TCP 1898 of the container and pointed the EVB to it. In my Docker container log i see activity, so running this code in Docker looks to be no problem. Parsing the data is not working correctly, but i think that is not related to Docker. I have created a separate issue for it #3

**Comment by ThinkPadNL** [comment]
This sunny 🌞 morning and the panels generating >100W i have the same issue with the script crashing. 
Any idea what is going wrong @zivillian ?

**Comment by zivillian** [comment]
it would be great if you create a PR with your final Dockerfile

**Comment by ThinkPadNL** [comment]
Sure, no problem. See #4 
I'm not sure if python 3.9 alpine is the exact version that is needed, as i am not a programmer and don't use Python daily to know enough about their way to number their versions. The `-alpine` version is needed for sure because the normal version lacks `git` (and maybe more like `sed`).
