### ISSUE TITLE
Ported the code to Node-RED

### ISSUE THREAD

**Issue by ThinkPadNL** [zivillian/enverproxy#6]
Some nice thing i would like to share.

I had the Python-script running in Docker + a MQTT-container beside it for a few days and worked quite good. But it felt a bit 'bulky' for me as i don't use MQTT anywhere else. For monitoring my panels i had to run two containers. Most of my home automation stuff i do in [Node-RED](https://nodered.org) so i thought: why not try to port the code of this project to Node-RED.

I managed to do it 😄 
![2022-05-12 07_39_03](https://user-images.githubusercontent.com/12446338/167999804-4a384293-39ff-4ee4-ab8d-9385426679bd.png)

You can find the JavaScript-code here: https://gathering.tweakers.net/forum/list_message/71502554#71502554
Backup link: https://gist.github.com/ThinkPadNL/4dd4e000d94d714a1b62f9ab9530d41e

The code is 'static', as in: you will have to define the inverters in the code by yourself. I used [HexEd.it](https://hexed.it) to work through the Enverbridge datapackets (sniffed by Wireshark). Using a forEach method would be nicer (as the inverter data is stored in the package at fixed distances) but as i am not a programmer this was quite complex for me. I only have a few panels, so searching the right bytes and defining them by hand in the script was OK for me.

This is not really a issue, so i will close it again, but i thought it would be nice to share it here. Maybe it is useful for someone.

**Comment by bierbauch1** [comment]
Hello, when I import it, Node RED says to me: Error: Input is not a JSON array.
What´s wrong?

**Comment by Impact123** [comment]
It's JavaScript code one can put into a `function` node. You can't import it.
